export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const MARK_TODO_SUCCESS   = 'MARK_TODO_SUCCESS';
export const UNMARK_TODO_SUCCESS = 'UNMARK_TODO_SUCCESS';